version: "2"
services:
  web:
    image: golang:latest
    volumes:
      - .:/go/src/server
    working_dir: /go/src/server
    ports:
      - "8080:8080"
    command: go run server.go
    restart: always
