version: "2"
services:
  web:
    image: golang:latest
    volumes:
      - .:/go/src/server
    working_dir: /go/src/server
    ports:
      - "8080:8080"
    links:
      - db
      - redis
    environment:
      DB_URL: db:28015
      REDIS_URL: redis:6379
    command: go run server.go
  redis:
    image: redis:alpine
    command: redis-server --requirepass '${REDIS_PASS}'
    ports: 
      - "6375:6375"
    environment:
      - REDIS_REPLICATION_MODE=master
  db:
    image: rethinkdb:latest
    ports:
      - "9090:8080"
      - "28015:28015"
      - "29015:29015"
    volumes:
      - ./db_data:/data
    command: ['rethinkdb', '--initial-password', '${DB_PASS}', '--bind', 'all']
